project:
  type: website

website:
  title: "Francesco D'Amico"
  description: "Statistical mechanics of learning · PhD @ Sapienza"
  favicon: favicon.png
  site-url: "https://francill99.github.io/fdamico_website/"
  open-graph: true
  twitter-card: true

  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "Research"
        menu:
          - text: "Publications"
            href: publications.qmd
          - text: "Projects"
            href: projects.qmd
          - text: "Talks and Posters"
            href: talks.qmd
      - text: "Teaching"
        menu:
          - text: "Tutoring"
            href: tutoring.qmd
    right:
      - icon: github
        text: GitHub
        href: https://github.com/Francill99
      - icon: envelope
        text: "francesco.damico@uniroma1.it"
        href: "mailto:francesco.damico@uniroma1.it"

  page-footer:
    left: "© 2025 Francesco D'Amico"
    right: |
      Built with <a href="https://quarto.org" target="_blank" rel="noopener">Quarto</a>

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    toc-title: Contents
    smooth-scroll: true
    css: styles.css
    code-copy: true
    include-in-header:
      text: |
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXX"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-XXXXXXX');
        </script>
