---
title: "Projects"
format:
  html:
    toc: true
    toc-depth: 2
---

## Master's degree

### Excellence program

- *Tecniche osservative e modellistiche per lo studio dell’atmosfera e del clima* (Observative and theoretical techniques for the study of atmosphere and climate)  🔽 [Slides](files/talks/2025/Presentazione_neural_scaling_laws.pdf)

### Thesis

- *The random features p-spin Hopfield model* 🔽 [Poster](files/talks/2025/Poster_pseudo_likelihood (3).pdf)

### Laboratory experiences

- *Biophysics laboratory*: Studio dei siti di binding di complessi proteici e analisi dell’affinità di legame attraverso modelli di machine learning 🔽 [Poster](files/talks/2025/Poster_pseudo_likelihood (3).pdf)

- *Computational physics - statistical mechanics*: Simulazione Montecarlo di un ensamble NPT di Hard Boxes 🔽 [Poster](files/talks/2025/Poster_pseudo_likelihood (3).pdf)

## Bachelor degree

### Excellence program

- *Green method*  

  Study of a one-dimensional oscillator with a general force applied 🔽 [Slides](files/talks/2024/SISSA_HSA.pdf)

  Green method to solve the Laplacian equation of electric potential given a general charge distribution 🔽 [Slides](files/talks/2024/SISSA_HSA.pdf)

- *Montecarlo methods for statistical mecanics*

  Numerical simulation and analysis of the phase transition in 2-D Ising model 🔽 [Slides](files/talks/2024/SISSA_HSA.pdf)
  
### Thesis

- *Modello di Vicsek topologico analizzato con tecniche di Machine Learning* (Topological Vicsek model analyzed with Machine Learning methods) 🔽 [Slides](files/talks/2024/SISSA_HSA.pdf)

- *Self-attention as an attractor network: transient memories without backpropagation*  🔽 [Poster](files/talks/2024/Poster_Cargese.pdf)

  ROccella Conference on Inference and AI, Roccella Ionica, **1-5/09/24**

  SISSA Journal Club — Trieste, **11/10/2024**  
  
