---
title: "Talks and Posters"
format:
  html:
    toc: true
    toc-depth: 2
---

## 2025

### Talks

- **Scaling laws, from Perceptrons to Deep Networks** 🔽 [Slides](files/talks/2025/chimera_journal_club_slides.pdf)

  Chimera group Journal Club - Sapienza, **07/10/2025** 

### Posters

- **Pseudo-likelihood produces associative memories able to generalize, even for asymmetric couplings** 🔽 [Poster](files/talks/2025/PL_poster.pdf)

  Mathematical Methods for High-Dimensional Data, Sapienza University of Rome, **8-12/09/25**

  STATPHYS29, Firenze, **13-17/07/25**

- **Implicit bias produces neural scaling laws in learning curves, from perceptrons to deep networks** 🔽 [Poster](files/talks/2025/PW_poster.pdf)

  ROccella Conference on Inference and AI, Roccella Ionica, **1-5/09/25**

  Learning and Optimization in High Dimensions, Bocconi Univeristy, Milano, **8-11/07/25**

  Beg Rohu summer school, Saint-Pierre-Quiberon, **2-14/06/25**

## 2024

### Talks

- *Self-attention as an attractor network: transient memories without backpropagation*  🔽 [Slides](files/talks/2024/sissa_journal_club_2024_slides.pdf)
  
  SISSA Journal Club — Trieste, **11/10/2024**  
  
### Posters
- *Self-attention as an attractor network: transient memories without backpropagation*  🔽 [Poster](files/talks/2024/SA_poster.pdf)

  ROccella Conference on Inference and AI, Roccella Ionica, **1-5/09/24**

  SISSA Journal Club — Trieste, **11/10/2024**  
  
