name: Update publications from Scholar

on:
  schedule:
    - cron: "0 4 * * 1"      # Mondays 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write       # needed to push built site / updates
  pages: write          # (optional) if using GitHub Pages deploy
  id-token: write       # (optional) for pages OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install scholarly pyyaml

      - name: Update publications.bib
        run: |
          python scripts/update_scholar_bib.py fcoliR8AAAAJ

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages (gh-pages branch)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

